from sqlalchemy import text
from sqlalchemy.engine import Engine


def apply_compatibility_migrations(engine: Engine) -> None:
    statements = [
        "ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS description TEXT",
        "ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS document_type VARCHAR(40)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS document_number VARCHAR(80)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS plan_id INTEGER REFERENCES saas_plans(id)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS logo_url VARCHAR(420)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) DEFAULT '#15956f' NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(20) DEFAULT '#2563eb' NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS timezone VARCHAR(80) DEFAULT 'America/Bogota' NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "UPDATE tenants SET document_number = tax_id WHERE document_number IS NULL AND tax_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_tenants_document_number ON tenants (document_number)",
        "CREATE INDEX IF NOT EXISTS ix_tenants_plan_id ON tenants (plan_id)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS phone VARCHAR(80)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS title VARCHAR(120)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS leader_id INTEGER REFERENCES users(id)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_users_leader_id ON users (leader_id)",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS base_price INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS max_storage_mb INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS max_records INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS includes_ai BOOLEAN DEFAULT false NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS includes_advanced_bi BOOLEAN DEFAULT false NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "ALTER TABLE IF EXISTS tenant_subscriptions ADD COLUMN IF NOT EXISTS renewal_date TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS tenant_subscriptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS module_id INTEGER REFERENCES modules(id)",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT true NOT NULL",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS enabled_at TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS configuration_json TEXT",
        "UPDATE tenant_modules SET is_enabled = enabled WHERE enabled IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_tenant_modules_module_id ON tenant_modules (module_id)",
        "ALTER TABLE IF EXISTS menu_items ADD COLUMN IF NOT EXISTS required_permission VARCHAR(120)",
        "UPDATE menu_items SET required_permission = required_permission_code WHERE required_permission IS NULL AND required_permission_code IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_menu_items_required_permission ON menu_items (required_permission)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS assigned_user_id INTEGER REFERENCES users(id)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS city VARCHAR(120)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS segment VARCHAR(120)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS obligation VARCHAR(180)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS original_balance INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS risk VARCHAR(40) DEFAULT 'Medio' NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS next_action VARCHAR(240)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS contactability VARCHAR(40) DEFAULT 'Media' NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS last_contact_at TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS next_contact_at TIMESTAMP WITH TIME ZONE",
        "UPDATE customers SET original_balance = balance WHERE original_balance = 0 AND balance > 0",
        "CREATE INDEX IF NOT EXISTS ix_customers_assigned_user_id ON customers (assigned_user_id)",
        """
        CREATE TABLE IF NOT EXISTS customer_obligations (
            id SERIAL PRIMARY KEY,
            tenant_id INTEGER NOT NULL REFERENCES tenants(id),
            project_id INTEGER REFERENCES projects(id),
            customer_id INTEGER NOT NULL REFERENCES customers(id),
            obligation_number VARCHAR(160) NOT NULL,
            product_type VARCHAR(120),
            portfolio_name VARCHAR(160),
            purchase_number VARCHAR(120),
            original_amount INTEGER DEFAULT 0 NOT NULL,
            current_balance INTEGER DEFAULT 0 NOT NULL,
            priority INTEGER DEFAULT 0 NOT NULL,
            capital_amount INTEGER,
            interest_amount INTEGER,
            fees_amount INTEGER,
            days_past_due INTEGER DEFAULT 0 NOT NULL,
            status VARCHAR(60) DEFAULT 'active' NOT NULL,
            risk VARCHAR(40) DEFAULT 'Medio' NOT NULL,
            due_date TIMESTAMP WITH TIME ZONE,
            assignment_date TIMESTAMP WITH TIME ZONE,
            assigned_user_id INTEGER REFERENCES users(id),
            assigned_leader_id INTEGER REFERENCES users(id),
            metadata_json TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT uq_customer_obligation_tenant_number UNIQUE (tenant_id, obligation_number)
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_customer_obligations_tenant_id ON customer_obligations (tenant_id)",
        "CREATE INDEX IF NOT EXISTS ix_customer_obligations_project_id ON customer_obligations (project_id)",
        "CREATE INDEX IF NOT EXISTS ix_customer_obligations_customer_id ON customer_obligations (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_customer_obligations_assigned_user_id ON customer_obligations (assigned_user_id)",
        "CREATE INDEX IF NOT EXISTS ix_customer_obligations_assigned_leader_id ON customer_obligations (assigned_leader_id)",
        "ALTER TABLE IF EXISTS customer_obligations ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS customer_obligations ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS customer_obligations ADD COLUMN IF NOT EXISTS assignment_date TIMESTAMP WITH TIME ZONE",
        """
        CREATE TABLE IF NOT EXISTS operational_sheet_rows (
            id SERIAL PRIMARY KEY,
            tenant_id INTEGER NOT NULL REFERENCES tenants(id),
            project_id INTEGER REFERENCES projects(id),
            user_id INTEGER NOT NULL REFERENCES users(id),
            customer_id INTEGER REFERENCES customers(id),
            obligation_id INTEGER REFERENCES customer_obligations(id),
            date DATE,
            portfolio VARCHAR(180),
            customer_name VARCHAR(220),
            document VARCHAR(80),
            obligation_number VARCHAR(180),
            management_note TEXT,
            commitment TEXT,
            amount INTEGER DEFAULT 0 NOT NULL,
            status VARCHAR(60) DEFAULT 'Pendiente' NOT NULL,
            next_action_at TIMESTAMP WITH TIME ZONE,
            metadata_json TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_operational_sheet_rows_tenant_id ON operational_sheet_rows (tenant_id)",
        "CREATE INDEX IF NOT EXISTS ix_operational_sheet_rows_project_id ON operational_sheet_rows (project_id)",
        "CREATE INDEX IF NOT EXISTS ix_operational_sheet_rows_user_id ON operational_sheet_rows (user_id)",
        "CREATE INDEX IF NOT EXISTS ix_operational_sheet_rows_customer_id ON operational_sheet_rows (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_operational_sheet_rows_obligation_id ON operational_sheet_rows (obligation_id)",
        "CREATE INDEX IF NOT EXISTS ix_operational_sheet_rows_status ON operational_sheet_rows (status)",
        "ALTER TABLE IF EXISTS management_activities ADD COLUMN IF NOT EXISTS obligation_id INTEGER REFERENCES customer_obligations(id)",
        "ALTER TABLE IF EXISTS payment_promises ADD COLUMN IF NOT EXISTS obligation_id INTEGER REFERENCES customer_obligations(id)",
        "ALTER TABLE IF EXISTS payment_agreements ADD COLUMN IF NOT EXISTS obligation_id INTEGER REFERENCES customer_obligations(id)",
        "ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS obligation_id INTEGER REFERENCES customer_obligations(id)",
        "CREATE INDEX IF NOT EXISTS ix_management_activities_customer_id ON management_activities (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_management_activities_tenant_id ON management_activities (tenant_id)",
        "CREATE INDEX IF NOT EXISTS ix_management_activities_obligation_id ON management_activities (obligation_id)",
        "CREATE INDEX IF NOT EXISTS ix_payment_promises_customer_id ON payment_promises (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_payment_promises_obligation_id ON payment_promises (obligation_id)",
        "CREATE INDEX IF NOT EXISTS ix_payment_agreements_obligation_id ON payment_agreements (obligation_id)",
        "CREATE INDEX IF NOT EXISTS ix_payments_customer_id ON payments (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_payments_obligation_id ON payments (obligation_id)",
        "ALTER TABLE IF EXISTS customer_demographics ADD COLUMN IF NOT EXISTS contactability VARCHAR(40) DEFAULT 'Media' NOT NULL",
        "ALTER TABLE IF EXISTS customer_demographics ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS customer_demographics ADD COLUMN IF NOT EXISTS valid_from DATE",
        "ALTER TABLE IF EXISTS customer_demographics ADD COLUMN IF NOT EXISTS valid_until DATE",
        "ALTER TABLE IF EXISTS call_logs ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id)",
        "CREATE INDEX IF NOT EXISTS ix_call_logs_project_id ON call_logs (project_id)",
        "ALTER TABLE IF EXISTS user_project_assignments ADD COLUMN IF NOT EXISTS tenant_id INTEGER REFERENCES tenants(id)",
        "ALTER TABLE IF EXISTS user_project_assignments ADD COLUMN IF NOT EXISTS role_in_project VARCHAR(40) DEFAULT 'agent' NOT NULL",
        "ALTER TABLE IF EXISTS user_project_assignments ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL",
        "ALTER TABLE IF EXISTS user_project_assignments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        """
        UPDATE user_project_assignments upa
        SET tenant_id = projects.tenant_id
        FROM projects
        WHERE upa.project_id = projects.id AND upa.tenant_id IS NULL
        """,
        "UPDATE user_project_assignments SET role_in_project = 'agent' WHERE role_in_project IS NULL",
        "UPDATE user_project_assignments SET is_active = true WHERE is_active IS NULL",
        "CREATE INDEX IF NOT EXISTS ix_user_project_assignments_tenant_id ON user_project_assignments (tenant_id)",
        "CREATE INDEX IF NOT EXISTS ix_user_project_assignments_user_id ON user_project_assignments (user_id)",
        "CREATE INDEX IF NOT EXISTS ix_user_project_assignments_project_id ON user_project_assignments (project_id)",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS module VARCHAR(80)",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS object_type VARCHAR(120)",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS object_id INTEGER",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS old_value TEXT",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS new_value TEXT",
        "UPDATE audit_logs SET object_type = entity_type WHERE object_type IS NULL",
        "UPDATE audit_logs SET object_id = entity_id WHERE object_id IS NULL",
        "UPDATE audit_logs SET old_value = before_json WHERE old_value IS NULL",
        "UPDATE audit_logs SET new_value = after_json WHERE new_value IS NULL",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_module ON audit_logs (module)",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_object_type ON audit_logs (object_type)",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_object_id ON audit_logs (object_id)",
    ]
    with engine.begin() as connection:
        for statement in statements:
            connection.execute(text(statement))
