from sqlalchemy import text
from sqlalchemy.engine import Engine


def apply_compatibility_migrations(engine: Engine) -> None:
    statements = [
        "ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS description TEXT",
        "ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS document_type VARCHAR(40)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS document_number VARCHAR(80)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS plan_id INTEGER REFERENCES saas_plans(id)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS logo_url VARCHAR(420)",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) DEFAULT '#15956f' NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(20) DEFAULT '#2563eb' NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS timezone VARCHAR(80) DEFAULT 'America/Bogota' NOT NULL",
        "ALTER TABLE IF EXISTS tenants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "UPDATE tenants SET document_number = tax_id WHERE document_number IS NULL AND tax_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_tenants_document_number ON tenants (document_number)",
        "CREATE INDEX IF NOT EXISTS ix_tenants_plan_id ON tenants (plan_id)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS phone VARCHAR(80)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS title VARCHAR(120)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS leader_id INTEGER REFERENCES users(id)",
        "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_users_leader_id ON users (leader_id)",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS base_price INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS max_storage_mb INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS max_records INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS includes_ai BOOLEAN DEFAULT false NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS includes_advanced_bi BOOLEAN DEFAULT false NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL",
        "ALTER TABLE IF EXISTS saas_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "ALTER TABLE IF EXISTS tenant_subscriptions ADD COLUMN IF NOT EXISTS renewal_date TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS tenant_subscriptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS module_id INTEGER REFERENCES modules(id)",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT true NOT NULL",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS enabled_at TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS tenant_modules ADD COLUMN IF NOT EXISTS configuration_json TEXT",
        "UPDATE tenant_modules SET is_enabled = enabled WHERE enabled IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_tenant_modules_module_id ON tenant_modules (module_id)",
        "ALTER TABLE IF EXISTS menu_items ADD COLUMN IF NOT EXISTS required_permission VARCHAR(120)",
        "UPDATE menu_items SET required_permission = required_permission_code WHERE required_permission IS NULL AND required_permission_code IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS ix_menu_items_required_permission ON menu_items (required_permission)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS assigned_user_id INTEGER REFERENCES users(id)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS city VARCHAR(120)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS segment VARCHAR(120)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS obligation VARCHAR(180)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS original_balance INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS risk VARCHAR(40) DEFAULT 'Medio' NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0 NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS next_action VARCHAR(240)",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS contactability VARCHAR(40) DEFAULT 'Media' NOT NULL",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS last_contact_at TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS next_contact_at TIMESTAMP WITH TIME ZONE",
        "UPDATE customers SET original_balance = balance WHERE original_balance = 0 AND balance > 0",
        "CREATE INDEX IF NOT EXISTS ix_customers_assigned_user_id ON customers (assigned_user_id)",
        "CREATE INDEX IF NOT EXISTS ix_management_activities_customer_id ON management_activities (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_management_activities_tenant_id ON management_activities (tenant_id)",
        "CREATE INDEX IF NOT EXISTS ix_payment_promises_customer_id ON payment_promises (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_payments_customer_id ON payments (customer_id)",
        "CREATE INDEX IF NOT EXISTS ix_user_project_assignments_user_id ON user_project_assignments (user_id)",
        "CREATE INDEX IF NOT EXISTS ix_user_project_assignments_project_id ON user_project_assignments (project_id)",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS module VARCHAR(80)",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS object_type VARCHAR(120)",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS object_id INTEGER",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS old_value TEXT",
        "ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS new_value TEXT",
        "UPDATE audit_logs SET object_type = entity_type WHERE object_type IS NULL",
        "UPDATE audit_logs SET object_id = entity_id WHERE object_id IS NULL",
        "UPDATE audit_logs SET old_value = before_json WHERE old_value IS NULL",
        "UPDATE audit_logs SET new_value = after_json WHERE new_value IS NULL",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_module ON audit_logs (module)",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_object_type ON audit_logs (object_type)",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_object_id ON audit_logs (object_id)",
    ]
    with engine.begin() as connection:
        for statement in statements:
            connection.execute(text(statement))
